version: "3"
services:
  snell:
    build: .
    restart: always
    network_mode: "host"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=<port>
      - OBFS=http
      - PSK=<password>
    # When using network_mode: "host", port mappings are not needed
    # as the container shares the host's network stack
