version: "3"
services:
  snell:
    build: .
    restart: always
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=<port>
      - OBFS=http
      - PSK=<password>
    ports:
      - "<port>:<port>/tcp"
      - "<port>:<port>/udp"
